version: "3.3"

services:
  adapter:
    build: .
    # image: donmichael/fusion_adapter
    environment:
      - BOOTSTRAP_SERVER=88.28.218.13:9097
      - SCHEMA_REGISTRY=http://88.28.218.13:8081
    command: >
      sh -c "python consumer.py"
    depends_on:
      - redis
  redis:
    image: redis:5
